config/routes.rb
Rails.application.routes.draw do
  resources :manufactures
  get    '/top', to: 'top#index'
  get    '/thanks', to: 'static_pages#thanks'
  post '/mailcompany', to: 'companies#mail', as: :companymail;
  post '/mail', to: 'npos#mail', as: :mail;
  resources :articles
  resources :occupations
  resources :companies
  resources :npos
  get    '/postarticle',   to: 'postarticles#index'
  root to: 'home#index'
  get 'sitemap', to: redirect('https://prlabbacket.s3.us-east-2.amazonaws.com/sitemaps/sitemap.xml.gz')
  get 'sitemap2', to: redirect('https://s3-us-east-2.amazonaws.com/prlabbacket/sitemaps2/sitemap.xml.gz')
end

app/models/company.rb
class Company < ApplicationRecord
    mount_uploader :img, ImgUploader

    def self.search(search) #self.はUser.を意味する
        if search
            where(['corporate_name LIKE ?', "%#{search}%"]) #検索とuseanameの部分一致を表示。
        else
            all #全て表示させる
        end
    end
end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController
  before_action :set_company, only: [:show, :edit, :update, :destroy]

  # GET /companies
  # GET /companies.json
  def index
    @companies = Company.page(params[:page]).search(params[:search])
  end

  def mail
    TestMailer.testmail(params[:corporate_name],params[:name],params[:email],params[:text]).deliver_later  #メーラに作成したメソッドを呼び出す。
    redirect_to controller: 'static_pages', action: 'thanks'
  end

  # GET /companies/1
  # GET /companies/1.json
  def show
  end

  # GET /companies/new
  def new
    @company = Company.new
  end

  # GET /companies/1/edit
  def edit
  end

  # POST /companies
  # POST /companies.json
  def create
    @company = Company.new(company_params)

    respond_to do |format|
      if @company.save
        format.html { redirect_to @company, notice: 'Company was successfully created.' }
        format.json { render :show, status: :created, location: @company }
      else
        format.html { render :new }
        format.json { render json: @company.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /companies/1
  # PATCH/PUT /companies/1.json
  def update
    respond_to do |format|
      if @company.update(company_params)
        format.html { redirect_to @company, notice: 'Company was successfully updated.' }
        format.json { render :show, status: :ok, location: @company }
      else
        format.html { render :edit }
        format.json { render json: @company.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /companies/1
  # DELETE /companies/1.json
  def destroy
    @company.destroy
    respond_to do |format|
      format.html { redirect_to companies_url, notice: 'Company was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_company
      @company = Company.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def company_params
      params.require(:company).permit(:corporate_name, :postal_code, :address, :pr, :img, :remove_img, :representative, :establishment, :capital, :tel_number, :work_field)
    end
end

app/helpers/companies_helper.rb
module CompaniesHelper
end

app/views/companies/_form.html.erb
<%= form_with(model: company, local: true) do |form| %>
  <% if company.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(company.errors.count, "error") %> prohibited this company from being saved:</h2>

      <ul>
      <% company.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :corporate_name %>
    <%= form.text_field :corporate_name %>
  </div>

  <div class="field">
    <%= form.label :postal_code %>
    <%= form.text_field :postal_code %>
  </div>

  <div class="field">
    <%= form.label :address %>
    <%= form.text_field :address %>
  </div>
  
  <div class="field">
    <%= form.label :representative %>
    <%= form.text_field :representative %>
  </div>

  <div class="field">
    <%= form.label :tel_number %>
    <%= form.text_field :tel_number %>
  </div>

  <div class="field">
    <%= form.label :work_field %>
    <%= form.text_field :work_field %>
  </div>

  <div class="field">
    <%= form.label :establishment %>
    <%= form.text_field :establishment %>
  </div>

  <div class="field">
    <%= form.label :capital %>
    <%= form.text_field :capital %>
  </div>

  <div class="field">
    <%= form.label :pr %>
    <%= form.text_area :pr, :size => "60x15" %>
  </div>

  <div class="field">
   <%= form.label :img %>
   <%= form.file_field :img, class: "image" %>
  </div>

  <p><%= form.check_box :remove_img %>画像を削除する</p>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/companies/edit.html.erb
<% content_for :noindex do %>
<meta name="robots" content="noindex">
<% end %>

<h1>編集画面</h1>

<br>
<%= render 'form', company: @company %>

<%= link_to 'Show', @company %> |
<%= link_to 'Back', companies_path %>

app/views/companies/index.html.erb
<p id="notice"><%= notice %></p>
<% content_for :title do %>
  <%= "掲載企業一覧 | PR-LABO" %>
<% end %>
<% breadcrumb :companies %>

<div class="search-form">
<%= form_tag(companies_path, :method => "get") do %>
<%= text_field_tag :search,'',placeholder: "法人名を入力" %> 
<%= submit_tag "検索" ,:username => nil ,class: "button is-info"%> 
<% end %> 
</div>
<br>
<br>


<% @companies.each do |company| %>
    <div class="iconbox iconbox-pink">
    <div class="box-title box-head-pink"><%= link_to company.corporate_name, company %></div>
    <div class="iconbox-wrap">
    <div class="box-content">
    <p><%= company.pr %></p>
    </div>
    <div class="iconballoon">
    <div class="icon"><%= image_tag 'noimage.png', :size =>'70x70' %></div>
    </div>
    </div>
    </div>
<% end %>

<%= paginate(@companies) %>

app/views/companies/new.html.erb
<% content_for :noindex do %>
<meta name="robots" content="noindex">
<% end %>

<h1>New Company</h1>

<%= render 'form', company: @company %>

<%= link_to 'Back', companies_path %>

app/views/companies/show.html.erb
<p id="notice"><%= notice %></p>

<% text_unregisterd = "まだ情報が登録されていません。" %>

<% content_for :markup do %>
<script type="application/ld+json">
{
    "@context" : "https://schema.org",
    "@type" : "Organization",
    "name" : "<%= @company.corporate_name %>",
    "address": "<%= @company.address %>"
}
</script>
<% end %>

<% content_for :smallchat do %>
<script src="https://embed.small.chat/T0197V2KEN5G019K64PWHE.js" async></script>
<% end %>

<% content_for :title do %>
  <%= @company.corporate_name + "を詳しく紹介！広報・採用・情報発信なら | PR-LABO" %>
<% end %>

<h1 class="companytitle"><%= @company.corporate_name %></h1>
<br>
<% breadcrumb :company, @company %>
<br>
<div class="box27">
    <span class="box-title">会社紹介</span>
    <p><%= @company.pr.present? ? simple_format(@company.pr) : text_unregisterd %></p>
</div>

<br>
<div class="box27">
    <span class="box-title">採用情報</span>
    <p><%= @company.recruit.present? ? simple_format(@company.recruit) : text_unregisterd %></p>
</div>
<br>

<div class="box27">
    <span class="box-title">イベント情報</span>
    <p><%= @company.event.present? ? simple_format(@company.event) : text_unregisterd %></p>
</div>
<br>

<div class="box27">
    <span class="box-title">よくある質問</span>
    <p><%= @company.faq.present? ? simple_format(@company.faq) : text_unregisterd %></p>
</div>

<p>
  <%= image_tag @company.img.url if @company.img? %>
</p>

<table class="table03">
  <tr>
    <th>会社名</th>
    <td><%= @company.corporate_name %></td>
  </tr>
  <tr>
    <th>住所</th>
    <td><%= @company.address %></td>
  </tr>
  <tr>
    <th>郵便番号</th>
    <td><%= @company.postal_code %></td>
  </tr>
  <tr>
    <th>電話番号</th>
    <td>
    <%= @company.tel_number.present? ? @company.tel_number : text_unregisterd %>
    </td>
  </tr>
  <tr>
    <th>設立</th>
    <td><%= @company.establishment.present? ? @company.establisment : text_unregisterd %></td>
  </tr>
  <tr>
    <th>資本金</th>
    <td><%= @company.capital.present? ? @company.capital : text_unregisterd %></td>
  </tr>
  <tr>
    <th>事業領域</th>
    <td><%= @company.work_field.present? ? @company.work_field : text_unregisterd %></td>
  </tr>
  <tr>
    <th>代表者</th>
    <td><%= @company.representative? ? @company.representative : text_unregisterd %></td>
  </tr>
</table>

<div class="parent clearfix">
<% if params[:id].to_i > 1 %>
    <div class="left"><%= link_to '前のページへ', company_path(params[:id].to_i - 1) %></div>
<% end %>
<% if params[:id].to_i < 26956 %>
    <div class="right"><%= link_to '次のページへ', company_path(params[:id].to_i + 1) %></div>
<% end %>
</div>
<br>
<br>
<%= link_to '企業一覧へ', companies_path %>
<br>
<br>
<br>
<center>
<h1 class="form-h1">お問い合わせフォーム</h1>
<br>
<p>PR-LABOは「企業・法人の魅力を発信する」Webサービスです。</p>
<p>WEBを使った集客・採用活動を始めてみませんか？</p>
<p>不明点などあれば下記フォームからお気軽にお問い合わせください。</p>
<br>
<%= form_with url: companymail_path, local: true do |f| %>
  <div class="field">
    <strong><%= f.label :法人名 %></strong>
    <%= f.text_field :corporate_name, value: @company.corporate_name %>
  </div>
  <br>
  <div class="field">
    <strong><%= f.label :お名前 %></strong>
    <%= f.text_field :name %>
  </div>
  <br>
  <div class="field">
    <strong><%= f.label :メールアドレス %></strong>
    <%= f.text_field :email %>
  </div>
  <br>
    <div class="field">
    <strong><%= f.label :お問い合わせ内容 %></strong>
    <%= f.text_area :text , :size => "50x15", value: "例)このページに追加情報を掲載したいです。どうしたらいいですか？" %>
  </div>
  <div class="actions">
  <%= f.submit "送信" %>
  </div>
<% end %>
</center>