config/routes.rb
Rails.application.routes.draw do
  resources :manufactures
  get    '/top', to: 'top#index'
  get    '/thanks', to: 'static_pages#thanks'
  post '/mailcompany', to: 'companies#mail', as: :companymail;
  post '/mail', to: 'npos#mail', as: :mail;
  resources :articles
  resources :occupations
  resources :companies
  resources :npos
  get    '/postarticle',   to: 'postarticles#index'
  root to: 'home#index'
  get 'sitemap', to: redirect('https://prlabbacket.s3.us-east-2.amazonaws.com/sitemaps/sitemap.xml.gz')
  get 'sitemap2', to: redirect('https://s3-us-east-2.amazonaws.com/prlabbacket/sitemaps2/sitemap.xml.gz')
end

app/models/manufacture.rb
class Manufacture < ApplicationRecord
end

app/controllers/manufactures_controller.rb
class ManufacturesController < ApplicationController
  before_action :set_manufacture, only: [:show, :edit, :update, :destroy]

  # GET /manufactures
  # GET /manufactures.json
  def index
    @manufactures = Manufacture.all
  end

  # GET /manufactures/1
  # GET /manufactures/1.json
  def show
  end

  # GET /manufactures/new
  def new
    @manufacture = Manufacture.new
  end

  # GET /manufactures/1/edit
  def edit
  end

  # POST /manufactures
  # POST /manufactures.json
  def create
    @manufacture = Manufacture.new(manufacture_params)

    respond_to do |format|
      if @manufacture.save
        format.html { redirect_to @manufacture, notice: 'Manufacture was successfully created.' }
        format.json { render :show, status: :created, location: @manufacture }
      else
        format.html { render :new }
        format.json { render json: @manufacture.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /manufactures/1
  # PATCH/PUT /manufactures/1.json
  def update
    respond_to do |format|
      if @manufacture.update(manufacture_params)
        format.html { redirect_to @manufacture, notice: 'Manufacture was successfully updated.' }
        format.json { render :show, status: :ok, location: @manufacture }
      else
        format.html { render :edit }
        format.json { render json: @manufacture.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /manufactures/1
  # DELETE /manufactures/1.json
  def destroy
    @manufacture.destroy
    respond_to do |format|
      format.html { redirect_to manufactures_url, notice: 'Manufacture was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_manufacture
      @manufacture = Manufacture.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def manufacture_params
      params.require(:manufacture).permit(:corporate_name, :category, :industry, :address, :tel_number, :establishment, :capital, :employees, :postal_code, :official_site, :img, :pr)
    end
end

app/helpers/manufactures_helper.rb
module ManufacturesHelper
end

app/views/manufactures/_form.html.erb
<%= form_with(model: manufacture, local: true) do |form| %>
  <% if manufacture.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(manufacture.errors.count, "error") %> prohibited this manufacture from being saved:</h2>

      <ul>
      <% manufacture.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :corporate_name %>
    <%= form.text_field :corporate_name %>
  </div>

  <div class="field">
    <%= form.label :category %>
    <%= form.text_field :category %>
  </div>

  <div class="field">
    <%= form.label :industry %>
    <%= form.text_field :industry %>
  </div>

  <div class="field">
    <%= form.label :address %>
    <%= form.text_field :address %>
  </div>

  <div class="field">
    <%= form.label :tel_number %>
    <%= form.text_field :tel_number %>
  </div>

  <div class="field">
    <%= form.label :establishment %>
    <%= form.text_field :establishment %>
  </div>

  <div class="field">
    <%= form.label :capital %>
    <%= form.text_field :capital %>
  </div>

  <div class="field">
    <%= form.label :employees %>
    <%= form.text_field :employees %>
  </div>

  <div class="field">
    <%= form.label :postal_code %>
    <%= form.text_field :postal_code %>
  </div>

  <div class="field">
    <%= form.label :official_site %>
    <%= form.text_field :official_site %>
  </div>

  <div class="field">
    <%= form.label :img %>
    <%= form.text_field :img %>
  </div>

  <div class="field">
    <%= form.label :pr %>
    <%= form.text_area :pr %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/manufactures/edit.html.erb
<h1>Editing Manufacture</h1>

<%= render 'form', manufacture: @manufacture %>

<%= link_to 'Show', @manufacture %> |
<%= link_to 'Back', manufactures_path %>

app/views/manufactures/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Manufactures</h1>

<table>
  <thead>
    <tr>
      <th>Corporate name</th>
      <th>Category</th>
      <th>Industry</th>
      <th>Address</th>
      <th>Tel number</th>
      <th>Establishment</th>
      <th>Capital</th>
      <th>Employees</th>
      <th>Postal code</th>
      <th>Official site</th>
      <th>Img</th>
      <th>Pr</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @manufactures.each do |manufacture| %>
      <tr>
        <td><%= manufacture.corporate_name %></td>
        <td><%= manufacture.category %></td>
        <td><%= manufacture.industry %></td>
        <td><%= manufacture.address %></td>
        <td><%= manufacture.tel_number %></td>
        <td><%= manufacture.establishment %></td>
        <td><%= manufacture.capital %></td>
        <td><%= manufacture.employees %></td>
        <td><%= manufacture.postal_code %></td>
        <td><%= manufacture.official_site %></td>
        <td><%= manufacture.img %></td>
        <td><%= manufacture.pr %></td>
        <td><%= link_to 'Show', manufacture %></td>
        <td><%= link_to 'Edit', edit_manufacture_path(manufacture) %></td>
        <td><%= link_to 'Destroy', manufacture, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Manufacture', new_manufacture_path %>

app/views/manufactures/new.html.erb
<h1>New Manufacture</h1>

<%= render 'form', manufacture: @manufacture %>

<%= link_to 'Back', manufactures_path %>

app/views/manufactures/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Corporate name:</strong>
  <%= @manufacture.corporate_name %>
</p>

<p>
  <strong>Category:</strong>
  <%= @manufacture.category %>
</p>

<p>
  <strong>Industry:</strong>
  <%= @manufacture.industry %>
</p>

<p>
  <strong>Address:</strong>
  <%= @manufacture.address %>
</p>

<p>
  <strong>Tel number:</strong>
  <%= @manufacture.tel_number %>
</p>

<p>
  <strong>Establishment:</strong>
  <%= @manufacture.establishment %>
</p>

<p>
  <strong>Capital:</strong>
  <%= @manufacture.capital %>
</p>

<p>
  <strong>Employees:</strong>
  <%= @manufacture.employees %>
</p>

<p>
  <strong>Postal code:</strong>
  <%= @manufacture.postal_code %>
</p>

<p>
  <strong>Official site:</strong>
  <%= @manufacture.official_site %>
</p>

<p>
  <strong>Img:</strong>
  <%= @manufacture.img %>
</p>

<p>
  <strong>Pr:</strong>
  <%= @manufacture.pr %>
</p>

<%= link_to 'Edit', edit_manufacture_path(@manufacture) %> |
<%= link_to 'Back', manufactures_path %>