config/routes.rb
Rails.application.routes.draw do
  resources :manufactures
  get    '/top', to: 'top#index'
  get    '/thanks', to: 'static_pages#thanks'
  post '/mailcompany', to: 'companies#mail', as: :companymail;
  post '/mail', to: 'npos#mail', as: :mail;
  resources :articles
  resources :occupations
  resources :companies
  resources :npos
  get    '/postarticle',   to: 'postarticles#index'
  root to: 'home#index'
  get 'sitemap', to: redirect('https://prlabbacket.s3.us-east-2.amazonaws.com/sitemaps/sitemap.xml.gz')
  get 'sitemap2', to: redirect('https://s3-us-east-2.amazonaws.com/prlabbacket/sitemaps2/sitemap.xml.gz')
end

app/models/npo.rb
class Npo < ApplicationRecord

    mount_uploader :img, ImgUploader
    
    def self.search(search) #self.はUser.を意味する
        if search
            where(['corporate_name LIKE ?', "%#{search}%"]) #検索とuseanameの部分一致を表示。
        else
            all #全て表示させる
        end
    end
end

app/controllers/npos_controller.rb
class NposController < ApplicationController
  before_action :set_npo, only: [:show, :edit, :update, :destroy]

  # GET /npos
  # GET /npos.json
  def index
    @npos = Npo.page(params[:page]).search(params[:search])
  end

  def mail
    TestMailer.testmail(params[:corporate_name],params[:name],params[:email],params[:text]).deliver_later  #メーラに作成したメソッドを呼び出す。
    redirect_to controller: 'static_pages', action: 'thanks'
  end

  # GET /npos/1
  # GET /npos/1.json
  def show
  end

  # GET /npos/new
  def new
    @npo = Npo.new
  end

  # GET /npos/1/edit
  def edit
  end

  # POST /npos
  # POST /npos.json
  def create
    @npo = Npo.new(npo_params)

    respond_to do |format|
      if @npo.save
        format.html { redirect_to @npo, notice: 'Npo was successfully created.' }
        format.json { render :show, status: :created, location: @npo }
      else
        format.html { render :new }
        format.json { render json: @npo.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /npos/1
  # PATCH/PUT /npos/1.json
  def update
    respond_to do |format|
      if @npo.update(npo_params)
        format.html { redirect_to @npo, notice: 'Npo was successfully updated.' }
        format.json { render :show, status: :ok, location: @npo }
      else
        format.html { render :edit }
        format.json { render json: @npo.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /npos/1
  # DELETE /npos/1.json
  def destroy
    @npo.destroy
    respond_to do |format|
      format.html { redirect_to npos_url, notice: 'Npo was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_npo
      @npo = Npo.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def npo_params
      params.require(:npo).permit(:corporate_name, :prefecture, :address, :representative, :certification_date, :establish_purpose, :field, :pr, :img, :remove_img)
    end
end

app/helpers/npos_helper.rb
module NposHelper
end

app/views/npos/_form.html.erb
<%= form_with(model: npo, local: true) do |form| %>
  <% if npo.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(npo.errors.count, "error") %> prohibited this npo from being saved:</h2>

      <ul>
      <% npo.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :corporate_name %>
    <%= form.text_field :corporate_name %>
  </div>

  <div class="field">
    <%= form.label :prefecture %>
    <%= form.text_field :prefecture %>
  </div>

  <div class="field">
    <%= form.label :address %>
    <%= form.text_field :address %>
  </div>

  <div class="field">
    <%= form.label :representative %>
    <%= form.text_field :representative %>
  </div>

  <div class="field">
    <%= form.label :certification_date %>
    <%= form.text_field :certification_date %>
  </div>

  <div class="field">
    <%= form.label :establish_purpose %>
    <%= form.text_field :establish_purpose %>
  </div>

  <div class="field">
    <%= form.label :field %>
    <%= form.text_field :field %>
  </div>

  <div class="field">
    <%= form.label :pr %>
    <%= form.text_area :pr, :size => "60x15" %>
  </div>

  <div class="field">
   <%= form.label :img %>
   <%= form.file_field :img, class: "image" %>
  </div>

  <p><%= form.check_box :remove_img %>画像を削除する</p>  

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/npos/edit.html.erb
<% content_for :noindex do %>
<meta name="robots" content="noindex">
<% end %>


<h1>編集画面</h1>
<br>

<%= render 'form', npo: @npo %>

<%= link_to 'Show', @npo %> |
<%= link_to 'Back', npos_path %>

app/views/npos/index.html.erb
<p id="notice"><%= notice %></p>
<% content_for :title do %>
  <%= "掲載NPO一覧 | PR-LABO" %>
<% end %>

<% breadcrumb :npos %>
<div class="search-form">
<%= form_tag(npos_path, :method => "get") do %>
<%= text_field_tag :search,'',placeholder: "法人名を入力" %> 
<%= submit_tag "検索" ,:username => nil ,class: "button is-info"%> 
<% end %> 
</div>
<br>
<br>

<% @npos.each do |npo| %>
    <div class="iconbox iconbox-green">
    <div class="box-title box-head-green"><%= link_to npo.corporate_name, npo %></div>
    <div class="iconbox-wrap">
    <div class="box-content">
    <p><%= npo.field %></p>
    </div>
    <div class="iconballoon">
    <div class="icon"><%= image_tag 'noimage.png', :size =>'70x70' %></div>
    </div>
    </div>
    </div>
<% end %>

<%= paginate(@npos) %>

app/views/npos/new.html.erb
<% content_for :noindex do %>
<meta name="robots" content="noindex">
<% end %>

<h1>New Npo</h1>

<%= render 'form', npo: @npo %>

<%= link_to 'Back', npos_path %>

app/views/npos/show.html.erb
<p id="notice"><%= notice %></p>

<% text_unregisterd = "まだ情報が登録されていません。" %>

<% content_for :markup do %>
  <script type="application/ld+json">
{
    "@context" : "https://schema.org",
    "@type" : "Organization",
    "name" : "<%= @npo.corporate_name %>",
    "address": "<%= @npo.address %>",
    "founder":"<%= @npo.representative %>",
    "foundingDate":"<%= @npo.certification_date %>", 
    "description" : "<%= @npo.establish_purpose %>"
}
</script>
<% end %>

<% content_for :smallchat do %>
<script src="https://embed.small.chat/T0197V2KEN5G019K64PWHE.js" async></script>
<% end %>


<% content_for :title do %>
  <%= @npo.corporate_name + "を詳しく紹介！広報・採用・情報発信なら | PR-LABO" %>
<% end %>
<% breadcrumb :npo, @npo %>

<h1 class="companytitle"><%= @npo.corporate_name %></h1>
<br>

<div class="box27">
    <span class="box-title">法人紹介</span>
    <p><%= @npo.pr.present? ? simple_format(@npo.pr) : text_unregisterd %></p>
</div>
<br>
<div class="box27">
    <span class="box-title">採用情報</span>
    <p><%= @npo.recruit.present? ? simple_format(@npo.recruit) : text_unregisterd %></p>
</div>
<br>
<div class="box27">
    <span class="box-title">イベント情報</span>
    <p><%= @npo.event.present? ? simple_format(@npo.event) : text_unregisterd %></p>
</div>
<br>
<div class="box27">
    <span class="box-title">よくある質問</span>
    <p><%= @npo.faq.present? ? simple_format(@npo.faq) : text_unregisterd %></p>
</div>

<p>
  <%= image_tag @npo.img.url if @npo.img? %>
</p>

<table class="table03">
  <tr>
    <th>会社名</th>
    <td><%= @npo.corporate_name %></td>
  </tr>
  <tr>
    <th>住所</th>
    <td><%= @npo.address %></td>
  </tr>
  <tr>
    <th>代表者名</th>
    <td><%= @npo.representative %></td>
  </tr>
  <tr>
    <th>設立認証年月日</th>
    <td><%= @npo.certification_date %></td>
  </tr>
  <tr>
    <th>定款に記載された目的</th>
    <td><%= @npo.establish_purpose %></td>
  </tr>
  <tr>
    <th>分野</th>
    <td><%= @npo.field %></td>
  </tr>
</table>


<div class="parent clearfix">
<% if params[:id].to_i > 1 %>
    <div class="left"><%= link_to '前のページへ', npo_path(params[:id].to_i - 1) %></div>
<% end %>
<% if params[:id].to_i < 29478 %>
    <div class="right"><%= link_to '次のページへ', npo_path(params[:id].to_i + 1) %></div>
<% end %>
</div>
<br>
<br>
<%= link_to 'NPO法人一覧へ', npos_path %>
<br>
<br>
<br>
<center>
<h1 class="form-h1">お問い合わせフォーム</h1>
<br>
<p>PR-LABOは「企業・法人の魅力を発信する」Webサービスです。</p>
<p>WEBを使った集客・採用活動を始めてみませんか？</p>
<p>不明点などあれば下記フォームからお気軽にお問い合わせください。</p>
<br>
<%= form_with url: mail_path, local: true do |f| %>
  <div class="field">
    <strong><%= f.label :法人名 %></strong>
    <%= f.text_field :corporate_name, value: @npo.corporate_name %>
  </div>
  <br>
  <div class="field">
    <strong><%= f.label :お名前 %></strong>
    <%= f.text_field :name %>
  </div>
  <br>
  <div class="field">
    <strong><%= f.label :メールアドレス %></strong>
    <%= f.text_field :email %>
  </div>
  <br>
    <div class="field">
    <strong><%= f.label :お問い合わせ内容 %></strong>
    <%= f.text_area :text , :size => "50x15", value: "例)このページに追加で情報を掲載したいです。どうしたらいいですか？"  %>
  </div>
  <div class="actions">
  <%= f.submit "送信" %>
  </div>
<% end %>
</center>