config/routes.rb
Rails.application.routes.draw do
  resources :manufactures
  get    '/top', to: 'top#index'
  get    '/thanks', to: 'static_pages#thanks'
  post '/mailcompany', to: 'companies#mail', as: :companymail;
  post '/mail', to: 'npos#mail', as: :mail;
  resources :articles
  resources :occupations
  resources :companies
  resources :npos
  get    '/postarticle',   to: 'postarticles#index'
  root to: 'home#index'
  get 'sitemap', to: redirect('https://prlabbacket.s3.us-east-2.amazonaws.com/sitemaps/sitemap.xml.gz')
  get 'sitemap2', to: redirect('https://s3-us-east-2.amazonaws.com/prlabbacket/sitemaps2/sitemap.xml.gz')
end

app/views/layouts/_footer.html.erb
<footer>
  <ul class="nav-list">
    <li class="nav-list-item">
      <%= link_to 'Home', root_path %>
    </li>
    <li class="nav-list-item">
      <%= link_to 'NPO法人一覧', npos_path %>
    </li>
    <li class="nav-list-item">
      <%= link_to '企業一覧', companies_path %>
    </li>
    <li class="nav-list-item">
      <%= link_to '職業一覧', occupations_path %>
    </li>
    <li class="nav-list-item">
      <%= link_to 'コラム', articles_path %>
    </li>
  </ul>
</footer>

app/views/layouts/_google_tag_manager.html.erb
<!-- Google Tag Manager -->
<script>(function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':
new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],
j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src=
'https://www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f);
})(window,document,'script','dataLayer','GTM-5QQCP6R');</script>
<!-- End Google Tag Manager -->

app/views/layouts/_google_tag_manager_noscript.html.erb
<!-- Google Tag Manager (noscript) -->
<noscript><iframe src="https://www.googletagmanager.com/ns.html?id=GTM-5QQCP6R"
height="0" width="0" style="display:none;visibility:hidden"></iframe></noscript>
<!-- End Google Tag Manager (noscript) -->

app/views/layouts/_header.html.erb
<header>
<h1 id="heading08">PR-LABO</h1>
<br>
<p class="breadcrumbs"><%= breadcrumbs separator: " &rsaquo; " %><p>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <%= render 'layouts/google_tag_manager' if Rails.env.production? %>
    <%= yield :markup %>
    <%= yield :smallchat %>
    <%= yield :noindex %> 
    <meta name="description" content="PR-LABO(PRラボ)は、企業・NPO・研究会などあらゆる団体の情報発信を支援するWEBサービスです。インターネットに詳しくない方でも、気軽に情報を発信でき、組織の魅力を世の中に伝えられるサービスを目指しています。">
    <title><%= content_for?(:title) ? yield(:title) : "団体・組織・法人の魅力を伝えるなら | PR-LABO"%></title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <%= stylesheet_link_tag "application", media: "all",
                                           "data-turbolinks-track" => true %>
    <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
    <%= csrf_meta_tags %>
  </head>

  <body>
  <%= render 'layouts/google_tag_manager_noscript' if Rails.env.production? %>
  <%= render 'layouts/header' %>
    <%= yield %>
  <%= render 'layouts/footer' %>
  </body>
</html>